# Generated by Django 4.1.1 on 2023-05-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtor', '0002_rename_user_produtor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo_evento', models.CharField(max_length=100)),
                ('data_inicio', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('endereco', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('qtd_ingresso', models.CharField(max_length=100)),
                ('valor_ingresso', models.CharField(max_length=100)),
                ('taxa_univentos', models.BooleanField(default=False)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='static/')),
            ],
        ),
    ]
